# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13fe686f1929b72973ab138933b50f7a349a93d7cd032f9742c510725756a381fe267a4095a8bef2c43f54375baf38548cbf14741754d3f402e168cd1f3daa79

test:
  secret_key_base: eb5e89e3db6b99c615a2ac9dfba2b38bcc335bd2bf596ce067464ffa7856bb36c05168e21d95d75b1e3eb0f7987e0ae4f05c4abdd558cb7f18aca72014cb629b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
